/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-12-09 16:18:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Calculation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<style>\r\n");
      out.write("#invoice{\r\n");
      out.write("    padding: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    background-color: #FFF;\r\n");
      out.write("    min-height: 680px;\r\n");
      out.write("    padding: 15px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice header {\r\n");
      out.write("    padding: 10px 0;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("    border-bottom: 1px solid #3989c6\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice .company-details {\r\n");
      out.write("    text-align: right\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice .company-details .name {\r\n");
      out.write("    margin-top: 0;\r\n");
      out.write("    margin-bottom: 0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice .contacts {\r\n");
      out.write("    margin-bottom: 20px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice .invoice-to {\r\n");
      out.write("    text-align: left\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice .invoice-to .to {\r\n");
      out.write("    margin-top: 0;\r\n");
      out.write("    margin-bottom: 0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice .invoice-details {\r\n");
      out.write("    text-align: right\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice .invoice-details .invoice-id {\r\n");
      out.write("    margin-top: 0;\r\n");
      out.write("    color: #3989c6\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice main {\r\n");
      out.write("    padding-bottom: 50px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice main .thanks {\r\n");
      out.write("    margin-top: -100px;\r\n");
      out.write("    font-size: 2em;\r\n");
      out.write("    margin-bottom: 50px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice main .notices {\r\n");
      out.write("    padding-left: 6px;\r\n");
      out.write("    border-left: 6px solid #3989c6\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice main .notices .notice {\r\n");
      out.write("    font-size: 1.2em\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice table {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("    border-spacing: 0;\r\n");
      out.write("    margin-bottom: 20px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice table td,.invoice table th {\r\n");
      out.write("    padding: 15px;\r\n");
      out.write("    background: #eee;\r\n");
      out.write("    border-bottom: 1px solid #fff\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice table th {\r\n");
      out.write("    white-space: nowrap;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    font-size: 16px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice table td h3 {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    color: #3989c6;\r\n");
      out.write("    font-size: 1.2em\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice table .qty,.invoice table .total,.invoice table .unit {\r\n");
      out.write("    text-align: right;\r\n");
      out.write("    font-size: 1.2em\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice table .no {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-size: 1.6em;\r\n");
      out.write("    background: #3989c6\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice table .unit {\r\n");
      out.write("    background: #ddd\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice table .total {\r\n");
      out.write("    background: #3989c6;\r\n");
      out.write("    color: #fff\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice table tbody tr:last-child td {\r\n");
      out.write("    border: none\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice table tfoot td {\r\n");
      out.write("    background: 0 0;\r\n");
      out.write("    border-bottom: none;\r\n");
      out.write("    white-space: nowrap;\r\n");
      out.write("    text-align: right;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    font-size: 1.2em;\r\n");
      out.write("    border-top: 1px solid #aaa\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice table tfoot tr:first-child td {\r\n");
      out.write("    border-top: none\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice table tfoot tr:last-child td {\r\n");
      out.write("    color: #3989c6;\r\n");
      out.write("    font-size: 1.4em;\r\n");
      out.write("    border-top: 1px solid #3989c6\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice table tfoot tr td:first-child {\r\n");
      out.write("    border: none\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".invoice footer {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #777;\r\n");
      out.write("    border-top: 1px solid #aaa;\r\n");
      out.write("    padding: 8px 0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media print {\r\n");
      out.write("    .invoice {\r\n");
      out.write("        font-size: 11px!important;\r\n");
      out.write("        overflow: hidden!important\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .invoice footer {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        bottom: 10px;\r\n");
      out.write("        page-break-after: always\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .invoice>div:last-child {\r\n");
      out.write("        page-break-before: always\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" $('#printInvoice').click(function(){\r\n");
      out.write("            Popup($('.invoice')[0].outerHTML);\r\n");
      out.write("            function Popup(data) \r\n");
      out.write("            {\r\n");
      out.write("                window.print();\r\n");
      out.write("                return true;\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write(" </script>\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<!------ Include the above in your HEAD tag ---------->\r\n");
      out.write("<div id=\"invoice\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"toolbar hidden-print\">\r\n");
      out.write("        <div class=\"text-right\">\r\n");
      out.write("            <button id=\"printInvoice\" class=\"btn btn-info\"><i class=\"fa fa-print\"></i> Print</button>\r\n");
      out.write("            <button class=\"btn btn-info\"><i class=\"fa fa-file-pdf-o\"></i> Export as PDF</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"invoice overflow-auto\">\r\n");
      out.write("        <div style=\"min-width: 600px\">\r\n");
      out.write("            <header>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col\">\r\n");
      out.write("                        <a target=\"_blank\" href=\"Index.jsp\">\r\n");
      out.write("                            <img src=\"dummy/invoicelogo.jpg\" data-holder-rendered=\"true\" />\r\n");
      out.write("                            </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col company-details\">\r\n");
      out.write("                        <h2 class=\"name\">\r\n");
      out.write("                            <a target=\"_blank\" href=\"Index.jsp\">\r\n");
      out.write("                            Motor Insurance\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </h2>\r\n");
      out.write("                        <div>Pune, EON Free Zone </div>\r\n");
      out.write("                        <div>Kharadi, Pune</div>\r\n");
      out.write("                        <div>Maharashtra 411014</div>\r\n");
      out.write("                        <div>motorinsurance@outlook.com</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </header>\r\n");
      out.write("            <main>\r\n");
      out.write("                <div class=\"row contacts\">\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"col invoice-details\">\r\n");
      out.write("                        <h1 class=\"invoice-id\">INVOICE 3-2-1</h1>\r\n");
      out.write("                        <div class=\"date\">");
      out.print( (new java.util.Date()).toLocaleString());
      out.write("</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>#</th>\r\n");
      out.write("                            <th class=\"text-left\">DESCRIPTION</th>\r\n");
      out.write("                            <th class=\"text-right\">TOTAL</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td class=\"no\">01</td>\r\n");
      out.write("                            <td class=\"text-left\"><h3>IDV</h3>Insured Declared Value</td>\r\n");
      out.write("                            <td class=\"total\">$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idv}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td class=\"no\">02</td>\r\n");
      out.write("                            <td class=\"text-left\"><h3>Basic Premium</h3>Basic Premium Without Taxes</td>\r\n");
      out.write("                            <td class=\"total\">$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${netPremium}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td class=\"no\">03</td>\r\n");
      out.write("                            <td class=\"text-left\"><h3>Risk Tax</h3>Only For Commercial Vehical </td>\r\n");
      out.write("                            <td class=\"total\">$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Commercial}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td class=\"no\">04</td>\r\n");
      out.write("                            <td class=\"text-left\"><h3>road Tax</h3>Road and Toll Tax</td>\r\n");
      out.write("                            <td class=\"total\">$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roadTax}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                    <tfoot>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td colspan=\"0\"></td>\r\n");
      out.write("                            <td colspan=\"0\">SUBTOTAL</td>\r\n");
      out.write("                            <td>$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${subtotal}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td colspan=\"0\"></td>\r\n");
      out.write("                            <td colspan=\"0\">TAX 18%</td>\r\n");
      out.write("                            <td>$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gst}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td colspan=\"0\"></td>\r\n");
      out.write("                            <td colspan=\"0\">Grant Premium</td>\r\n");
      out.write("                            <td>$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${premium}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tfoot>\r\n");
      out.write("                </table>\r\n");
      out.write("                <div class=\"thanks\">Thank you!</div>\r\n");
      out.write("                <div class=\"notices\">\r\n");
      out.write("                    <div>NOTICE:</div>\r\n");
      out.write("                    <div class=\"notice\">Please Insured Your Car with Us \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </main>\r\n");
      out.write("            <footer>\r\n");
      out.write("                Invoice was created on a computer and is valid without the signature and seal.\r\n");
      out.write("            </footer>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--DO NOT DELETE THIS div. IT is responsible for showing footer always at the bottom-->\r\n");
      out.write("        <div></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
