/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-12-09 16:15:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta charset=\"UTF-8\">\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0,maximum-scale=1\">\n");
      out.write("\t\t\n");
      out.write("\t\t<title>Insurance</title>\n");
      out.write("\n");
      out.write("\t\t<!-- Loading third party fonts -->\n");
      out.write("\t\t<link href=\"http://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700|\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\t\t<link href=\"fonts/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\t\t<link href=\"fonts/lineo-icon/style.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\n");
      out.write("\t\t<!-- Loading main css file -->\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"style.css\">\n");
      out.write("\t\t\n");
      out.write("\t\t<!--[if lt IE 9]>\n");
      out.write("\t\t<script src=\"js/ie-support/html5.js\"></script>\n");
      out.write("\t\t<script src=\"js/ie-support/respond.js\"></script>\n");
      out.write("\t\t<![endif]-->\n");
      out.write("\n");
      out.write("\t</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<body>\n");
      out.write("\t\t\n");
      out.write("\t\t<div id=\"site-content\">\n");
      out.write("\t\t\t<header class=\"site-header\">\n");
      out.write("\t\t\t\t<div class=\"top-header\">\n");
      out.write("\t\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t<a href=\"index.html\" id=\"branding\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"https://watermann-zink.de/wp-content/uploads/2017/05/ALLIANZ-LOGO-1.png\" alt=\"Company Name\" class=\"logo\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"logo-text\">\n");
      out.write("\t\t\t\t\t\t\t\t<h1 class=\"site-title\">Allianz Technology</h1>\n");
      out.write("\t\t\t\t\t\t\t\t<small class=\"description\">Taline goes here</small>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</a> <!-- #branding -->\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<div class=\"right-section pull-right\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"phone\"><img src=\"images/icon-phone.png\" class=\"icon\">+1 823 424 9134</a>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<form action=\"VehicleCont\n");
      out.write("\t\t\t\t\t\t\troller\" class=\"search-form\" method=\"post\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Enter VehicleNumber\" name=\"vehiclenumber\" required=\"required\">\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\"><img src=\"images/icon-search.png\" alt=\"\"></button>\n");
      out.write("\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div> <!-- .container -->\n");
      out.write("\t\t\t\t</div> <!-- .top-header -->\n");
      out.write("\t\t\t\t<div class=\"bottom-header\">\n");
      out.write("\t\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t<div class=\"main-navigation\">\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"menu-toggle\"><i class=\"fa fa-bars\"></i></button>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"menu\">\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"menu-item\"><a href=\"about.jsp\n");
      out.write("\t\t\t\t\t\t\t\t\">About us</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"menu-item\"><a href=\"insurance.html\">Insurance plans</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"menu-item\"><a href=\"resource.html\">Resources</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"menu-item\"><a href=\"contact.jsp\">Contact</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul> <!-- .menu -->\n");
      out.write("\t\t\t\t\t\t</div> <!-- .main-navigation -->\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<div class=\"social-links\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"Login.jsp\">Login<i class=\"fa fa-facebook\"></i></a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"Register.jsp\">Register<i class=\"fa fa-twitter\"></i></a>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<div class=\"mobile-navigation\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</header> <!-- .site-header -->\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"hero hero-slider\">\n");
      out.write("\t\t\t\t<ul class=\"slides\">\n");
      out.write("\t\t\t\t\t<li data-bg-image=\"dummy/slide-1.jpg\">\n");
      out.write("\t\t\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"slide-content\">\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"slide-title\">Our Service Has No Speed Limit<strong></strong></h2>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"Home.jsp\" class=\"button\">Get a quote</a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li data-bg-image=\"dummy/slide-2.jpg\">\n");
      out.write("\t\t\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"slide-content\">\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"slide-title\">Our Service Has No Speed Limit<strong></strong></h2>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"Home.jsp\" class=\"button\">Get a quote</a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li data-bg-image=\"dummy/slide-3.jpg\">\n");
      out.write("\t\t\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"slide-content\">\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"slide-title\">Our Service Has No Speed Limit<strong></strong></h2>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"Home.jsp\" class=\"button\">Get a quote</a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div> <!-- .hero-slider -->\n");
      out.write("\n");
      out.write("\t\t\t<main class=\"main-content\">\n");
      out.write("\t\t\t\t<div class=\"fullwidth-block greet-section\">\n");
      out.write("\t\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t<h2 class=\"section-title\">Welcome to our website</h2>\n");
      out.write("\t\t\t\t\t\t<small class=\"section-subtitle\">Etiam suscipit leo tincidunt risus dignissim quisque semper mollis</small>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"feature\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-phone-24\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"feature-title\">24 hours Service</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor amet consectetur adipiscing elit do eiusmod tempor incididunt labore dolore magna aliqua.</p>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"feature\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-hotel\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"feature-title\">Hospitality</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor amet consectetur adipiscing elit do eiusmod tempor incididunt labore dolore magna aliqua.</p>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"feature\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-luggage\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"feature-title\">Praesent pellentesque </h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor amet consectetur adipiscing elit do eiusmod tempor incididunt labore dolore magna aliqua.</p>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"feature\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-credit-card-hand\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"feature-title\">Consectetur interdum</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor amet consectetur adipiscing elit do eiusmod tempor incididunt labore dolore magna aliqua.</p>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div> <!-- .row -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"text-center\">\n");
      out.write("\t\t\t\t\t\t\t<p>Sollicitudin sit tortor pellentesque. <a href=\"#\">Read more</a></p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div> <!-- .container -->\n");
      out.write("\t\t\t\t</div> <!-- .fullwidth-block -->\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"fullwidth-block\" data-bg-color=\"#f1f1f1\">\n");
      out.write("\t\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t<h2 class=\"section-title\">Our insurance offer</h2>\n");
      out.write("\t\t\t\t\t\t<small class=\"section-subtitle\">Phasellus vel felis in nulla mollis posuere eget rutrum eros</small>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"offer caption-top\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"dummy/offer-tall.jpg\" alt=\"offer 1\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"caption\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3 class=\"offer-title\">Massa augue</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<small>Conubia nostra per inceptos</small>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-9\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"offer caption-bottom\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"dummy/offer-1.jpg\" alt=\"offer 2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"caption\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"offer-title\">Curabitur vehicula</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<small>Conubia nostra per inceptos</small>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-8\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"offer caption-bottom\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"dummy/offer-wide.jpg\" alt=\"offer 3\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"caption\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3 class=\"offer-title\">Vivamus rhoncus porttitor</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<small>Conubia nostra per inceptos</small>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"offer caption-bottom\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"dummy/offer-2.jpg\" alt=\"offer 2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"caption\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"offer-title\">Curabitur vehicula</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<small>Conubia nostra per inceptos</small>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"offer caption-bottom\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"dummy/offer-3.jpg\" alt=\"offer 2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"caption\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"offer-title\">Curabitur vehicula</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<small>Conubia nostra per inceptos</small>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"offer caption-bottom\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"dummy/offer-4.jpg\" alt=\"offer 2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"caption\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"offer-title\">Curabitur vehicula</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<small>Conubia nostra per inceptos</small>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div> <!-- .row -->\n");
      out.write("\t\t\t\t\t\t\t</div> <!-- .col-md-8 -->\n");
      out.write("\t\t\t\t\t\t</div> <!-- .row -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div> <!-- .container -->\n");
      out.write("\t\t\t\t</div> <!-- .offer-section -->\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"fullwidth-block\">\n");
      out.write("\t\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t<h2 class=\"section-title\">Latest news</h2>\n");
      out.write("\t\t\t\t\t\t<div class=\"row news-list\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-4\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"news\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<figure><img src=\"dummy/featured-image-1.jpg\" alt=\"\"></figure>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"date\"><img src=\"images/icon-calendar.png\" alt=\"\">03/09/2014</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2 class=\"entry-title\"><a href=\"#\">Donec laoreet non nec aliquam pellentesque interdum</a></h2>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-4\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"news\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<figure><img src=\"dummy/featured-image-2.jpg\" alt=\"\"></figure>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"date\"><img src=\"images/icon-calendar.png\" alt=\"\">03/09/2014</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2 class=\"entry-title\"><a href=\"#\">Donec laoreet non nec aliquam pellentesque interdum</a></h2>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-4\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"news\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<figure><img src=\"dummy/featured-image-3.jpg\" alt=\"\"></figure>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"date\"><img src=\"images/icon-calendar.png\" alt=\"\">03/09/2014</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2 class=\"entry-title\"><a href=\"#\">Donec laoreet non nec aliquam pellentesque interdum</a></h2>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div> <!-- .row -->\n");
      out.write("\t\t\t\t\t</div> <!-- .container -->\n");
      out.write("\t\t\t\t</div> <!-- .latest-news-section -->\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"fullwidth-block\" data-bg-color=\"#0f75bd\">\n");
      out.write("\t\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t<div class=\"testimonial-slider\">\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"slides\">\n");
      out.write("\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<blockquote>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam quod explicabo optio quia ex odit, sequi harum voluptatibus autem. Nam autem corporis deleniti fugiat omnis itaque, quis laudantium dolor facere.<cite>John Smith</cite></blockquote>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<blockquote>At doloremque, itaque molestias neque nesciunt placeat aspernatur veniam fugit enim, dolor, re\n");
      out.write("\t\t\t\t\t\t\t\t\tpudiandae a. Laborum optio dolorum qui maxime doloribus eligendi in enim minima quo? Quis tenetur eos, libero exercitationem.<cite>John Smith</cite></blockquote>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<blockquote>Ipsam nesciunt velit voluptatem? Voluptas amet, porro eaque asperiores magni rerum vitae nulla inventore, numquam facilis doloribus placeat iure suscipit adipisci dolores modi saepe deserunt nisi. Nam, illum aperiam velit.<cite>John Smith</cite></blockquote>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div> <!-- .container -->\n");
      out.write("\t\t\t\t</div> <!-- .fullwidth-block -->\n");
      out.write("\t\t\t</main>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"site-footer\">\n");
      out.write("\t\t\t\t<div class=\"widget-area\">\n");
      out.write("\t\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-12 col-sm-4 col-md-2\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"widget\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"widget-title\">Contact</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t<address> Company Name INC. 523 Burt Street, Omaha\n");
      out.write("\t\t\t\t\t\t\t\t\t</address>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">Phone: +1 823 424 9134</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"mailto:info@company.com\">info@company.com</a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-12 col-sm-4 col-md-2\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"widget\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"widget-title\">Company</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"no-bullet\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">About us</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Infoline</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Team</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Join us</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Cooperation</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-12 col-sm-4 col-md-2\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"widget\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"widget-title\">Products</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"no-bullet\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Life insurance</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Home insurance</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Car insurance</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Business insurance</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Investment insurance</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-12 col-sm-4 col-md-2\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"widget\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"widget-title\">Our Solutions</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"no-bullet\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Presentation</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Testimonials</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Examples</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Our experts</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Resources</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-12 col-sm-4 col-md-2\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"widget\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"widget-title\">Press Room</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"no-bullet\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Advertisement</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Interviews</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Hot news</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Photos</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Marketing</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-12 col-sm-4 col-md-2\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"widget\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"widget-title\">Resources</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"no-bullet\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Sed imperdiet magna</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Pellentesque molestie</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Nulla luctus cursus</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Ligula vel lacinia</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Mauris scelerisque</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"bottom-footer\">\n");
      out.write("\t\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t<nav class=\"footer-navigation\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">Home</a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">About us</a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">Insurance plans</a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">Resources</a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">Contact</a>\n");
      out.write("\t\t\t\t\t\t</nav>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"colophon\">Copyright 2014 Company name. Designed by Themezy. All rights reserved.</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<script src=\"js/jquery-1.11.1.min.js\"></script>\n");
      out.write("\t\t<script src=\"http://maps.google.com/maps/api/js?sensor=false&amp;language=en\"></script>\n");
      out.write("\t\t<script src=\"js/plugins.js\"></script>\n");
      out.write("\t\t<script src=\"js/app.js\"></script>\n");
      out.write("\t\t\n");
      out.write("\t</body>\n");
      out.write("\n");
      out.write("</html>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
