/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-12-08 13:53:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<style>\n");
      out.write("#invoice {\n");
      out.write("\tpadding: 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice {\n");
      out.write("\tposition: relative;\n");
      out.write("\tbackground-color: #FFF;\n");
      out.write("\tmin-height: 680px;\n");
      out.write("\tpadding: 15px\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice header {\n");
      out.write("\tpadding: 10px 0;\n");
      out.write("\tmargin-bottom: 20px;\n");
      out.write("\tborder-bottom: 1px solid #3989c6\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice .company-details {\n");
      out.write("\ttext-align: right\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice .company-details .name {\n");
      out.write("\tmargin-top: 0;\n");
      out.write("\tmargin-bottom: 0\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice .contacts {\n");
      out.write("\tmargin-bottom: 20px\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice .invoice-to {\n");
      out.write("\ttext-align: left\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice .invoice-to .to {\n");
      out.write("\tmargin-top: 0;\n");
      out.write("\tmargin-bottom: 0\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice .invoice-details {\n");
      out.write("\ttext-align: right\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice .invoice-details .invoice-id {\n");
      out.write("\tmargin-top: 0;\n");
      out.write("\tcolor: #3989c6\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice main {\n");
      out.write("\tpadding-bottom: 50px\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice main .thanks {\n");
      out.write("\tmargin-top: -100px;\n");
      out.write("\tfont-size: 2em;\n");
      out.write("\tmargin-bottom: 50px\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice main .notices {\n");
      out.write("\tpadding-left: 6px;\n");
      out.write("\tborder-left: 6px solid #3989c6\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice main .notices .notice {\n");
      out.write("\tfont-size: 1.2em\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table {\n");
      out.write("\twidth: 100%;\n");
      out.write("\tborder-collapse: collapse;\n");
      out.write("\tborder-spacing: 0;\n");
      out.write("\tmargin-bottom: 20px\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table td, .invoice table th {\n");
      out.write("\tpadding: 15px;\n");
      out.write("\tbackground: #eee;\n");
      out.write("\tborder-bottom: 1px solid #fff\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table th {\n");
      out.write("\twhite-space: nowrap;\n");
      out.write("\tfont-weight: 400;\n");
      out.write("\tfont-size: 16px\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table td h3 {\n");
      out.write("\tmargin: 0;\n");
      out.write("\tfont-weight: 400;\n");
      out.write("\tcolor: #3989c6;\n");
      out.write("\tfont-size: 1.2em\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table .qty, .invoice table .total, .invoice table .unit {\n");
      out.write("\ttext-align: right;\n");
      out.write("\tfont-size: 1.2em\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table .no {\n");
      out.write("\tcolor: #fff;\n");
      out.write("\tfont-size: 1.6em;\n");
      out.write("\tbackground: #3989c6\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table .unit {\n");
      out.write("\tbackground: #ddd\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table .total {\n");
      out.write("\tbackground: #3989c6;\n");
      out.write("\tcolor: #fff\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table tbody tr:last-child td {\n");
      out.write("\tborder: none\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table tfoot td {\n");
      out.write("\tbackground: 0 0;\n");
      out.write("\tborder-bottom: none;\n");
      out.write("\twhite-space: nowrap;\n");
      out.write("\ttext-align: right;\n");
      out.write("\tpadding: 10px 20px;\n");
      out.write("\tfont-size: 1.2em;\n");
      out.write("\tborder-top: 1px solid #aaa\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table tfoot tr:first-child td {\n");
      out.write("\tborder-top: none\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table tfoot tr:last-child td {\n");
      out.write("\tcolor: #3989c6;\n");
      out.write("\tfont-size: 1.4em;\n");
      out.write("\tborder-top: 1px solid #3989c6\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table tfoot tr td:first-child {\n");
      out.write("\tborder: none\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice footer {\n");
      out.write("\twidth: 100%;\n");
      out.write("\ttext-align: center;\n");
      out.write("\tcolor: #777;\n");
      out.write("\tborder-top: 1px solid #aaa;\n");
      out.write("\tpadding: 8px 0\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media print {\n");
      out.write("\t.invoice {\n");
      out.write("\t\tfont-size: 11px !important;\n");
      out.write("\t\toverflow: hidden !important\n");
      out.write("\t}\n");
      out.write("\t.invoice footer {\n");
      out.write("\t\tposition: absolute;\n");
      out.write("\t\tbottom: 10px;\n");
      out.write("\t\tpage-break-after: always\n");
      out.write("\t}\n");
      out.write("\t.invoice>div:last-child {\n");
      out.write("\t\tpage-break-before: always\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write(" $('#printInvoice').click(function(){\n");
      out.write("            Popup($('.invoice')[0].outerHTML);\n");
      out.write("            function Popup(data) \n");
      out.write("            {\n");
      out.write("                window.print();\n");
      out.write("                return true;\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write(" </script>\n");
      out.write("\t<link\n");
      out.write("\t\thref=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\"\n");
      out.write("\t\trel=\"stylesheet\" id=\"bootstrap-css\">\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("\t<!------ Include the above in your HEAD tag ---------->\n");
      out.write("\t<div id=\"site-content\">\n");
      out.write("\t\t\t<header class=\"site-header\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div> <!-- .container -->\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t<div id=\"invoice\">\n");
      out.write("\n");
      out.write("\t\t<div class=\"toolbar hidden-print\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"invoice overflow-auto\">\n");
      out.write("\t\t\t<div style=\"min-width: 600px\">\n");
      out.write("\t\t\t\t<header>\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col\">\n");
      out.write("\t\t\t\t\t\t\t<a target=\"_blank\" href=\"Index.jsp\"> <img\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"dummy/invoicelogo.jpg\" data-holder-rendered=\"true\" />\n");
      out.write("\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col company-details\">\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"name\">\n");
      out.write("\t\t\t\t\t\t\t\t<a target=\"_blank\" href=\"Index.jsp\"> Allianz Motor Insurance </a>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</h2>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<p>Allianz General Insurance is a private general insurance\n");
      out.write("\t\t\t\t\t\t\t\tcompany in India. The company is a joint venture between Bajaj\n");
      out.write("\t\t\t\t\t\t\t\tFinserv Limited owned by the Bajaj Group of India and Allianz\n");
      out.write("\t\t\t\t\t\t\t\tSE, a German financial services company.</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</header>\n");
      out.write("\t\t\t\t<main>\n");
      out.write("\t\t\t\t<div class=\"row contacts\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"col invoice-details\">\n");
      out.write("\t\t\t\t\t\t<!-- <h1 class=\"invoice-id\">INVOICE 3-2-1</h1> -->\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("\n");
      out.write("<h1 class=\"invoice-id\">Thank You</h1>\n");
      out.write(" <div>Pune, EON Free Zone</div>\n");
      out.write("\t\t\t\t\t\t\t<div>Kharadi, Pune</div>\n");
      out.write("\t\t\t\t\t\t\t<div>Maharashtra 411014</div>\n");
      out.write("\t\t\t\t\t\t\t<div>motorinsurance@outlook.com</div> \n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!-- <div class=\"thanks\">Thank you!</div> -->\n");
      out.write("\t\t\t\t\t<div class=\"notices\">\n");
      out.write("\t\t\t\t\t\t<!--  <div>NOTICE:</div> -->\n");
      out.write("\t\t\t\t\t\t<div class=\"notice\">Please Insured Your Car with Us</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</main>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!--DO NOT DELETE THIS div. IT is responsible for showing footer always at the bottom-->\n");
      out.write("\t\t\t\t\t<div></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
