/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-12-08 13:53:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Calculation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<style>\n");
      out.write("#invoice{\n");
      out.write("    padding: 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice {\n");
      out.write("    position: relative;\n");
      out.write("    background-color: #FFF;\n");
      out.write("    min-height: 680px;\n");
      out.write("    padding: 15px\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice header {\n");
      out.write("    padding: 10px 0;\n");
      out.write("    margin-bottom: 20px;\n");
      out.write("    border-bottom: 1px solid #3989c6\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice .company-details {\n");
      out.write("    text-align: right\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice .company-details .name {\n");
      out.write("    margin-top: 0;\n");
      out.write("    margin-bottom: 0\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice .contacts {\n");
      out.write("    margin-bottom: 20px\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice .invoice-to {\n");
      out.write("    text-align: left\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice .invoice-to .to {\n");
      out.write("    margin-top: 0;\n");
      out.write("    margin-bottom: 0\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice .invoice-details {\n");
      out.write("    text-align: right\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice .invoice-details .invoice-id {\n");
      out.write("    margin-top: 0;\n");
      out.write("    color: #3989c6\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice main {\n");
      out.write("    padding-bottom: 50px\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice main .thanks {\n");
      out.write("    margin-top: -100px;\n");
      out.write("    font-size: 2em;\n");
      out.write("    margin-bottom: 50px\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice main .notices {\n");
      out.write("    padding-left: 6px;\n");
      out.write("    border-left: 6px solid #3989c6\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice main .notices .notice {\n");
      out.write("    font-size: 1.2em\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table {\n");
      out.write("    width: 100%;\n");
      out.write("    border-collapse: collapse;\n");
      out.write("    border-spacing: 0;\n");
      out.write("    margin-bottom: 20px\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table td,.invoice table th {\n");
      out.write("    padding: 15px;\n");
      out.write("    background: #eee;\n");
      out.write("    border-bottom: 1px solid #fff\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table th {\n");
      out.write("    white-space: nowrap;\n");
      out.write("    font-weight: 400;\n");
      out.write("    font-size: 16px\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table td h3 {\n");
      out.write("    margin: 0;\n");
      out.write("    font-weight: 400;\n");
      out.write("    color: #3989c6;\n");
      out.write("    font-size: 1.2em\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table .qty,.invoice table .total,.invoice table .unit {\n");
      out.write("    text-align: right;\n");
      out.write("    font-size: 1.2em\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table .no {\n");
      out.write("    color: #fff;\n");
      out.write("    font-size: 1.6em;\n");
      out.write("    background: #3989c6\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table .unit {\n");
      out.write("    background: #ddd\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table .total {\n");
      out.write("    background: #3989c6;\n");
      out.write("    color: #fff\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table tbody tr:last-child td {\n");
      out.write("    border: none\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table tfoot td {\n");
      out.write("    background: 0 0;\n");
      out.write("    border-bottom: none;\n");
      out.write("    white-space: nowrap;\n");
      out.write("    text-align: right;\n");
      out.write("    padding: 10px 20px;\n");
      out.write("    font-size: 1.2em;\n");
      out.write("    border-top: 1px solid #aaa\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table tfoot tr:first-child td {\n");
      out.write("    border-top: none\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table tfoot tr:last-child td {\n");
      out.write("    color: #3989c6;\n");
      out.write("    font-size: 1.4em;\n");
      out.write("    border-top: 1px solid #3989c6\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice table tfoot tr td:first-child {\n");
      out.write("    border: none\n");
      out.write("}\n");
      out.write("\n");
      out.write(".invoice footer {\n");
      out.write("    width: 100%;\n");
      out.write("    text-align: center;\n");
      out.write("    color: #777;\n");
      out.write("    border-top: 1px solid #aaa;\n");
      out.write("    padding: 8px 0\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media print {\n");
      out.write("    .invoice {\n");
      out.write("        font-size: 11px!important;\n");
      out.write("        overflow: hidden!important\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .invoice footer {\n");
      out.write("        position: absolute;\n");
      out.write("        bottom: 10px;\n");
      out.write("        page-break-after: always\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .invoice>div:last-child {\n");
      out.write("        page-break-before: always\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write(" $('#printInvoice').click(function(){\n");
      out.write("            Popup($('.invoice')[0].outerHTML);\n");
      out.write("            function Popup(data) \n");
      out.write("            {\n");
      out.write("                window.print();\n");
      out.write("                return true;\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write(" </script>\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\n");
      out.write("<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("<!------ Include the above in your HEAD tag ---------->\n");
      out.write("<div id=\"invoice\">\n");
      out.write("\n");
      out.write("    <div class=\"toolbar hidden-print\">\n");
      out.write("        <div class=\"text-right\">\n");
      out.write("            <button id=\"printInvoice\" class=\"btn btn-info\"><i class=\"fa fa-print\"></i> Print</button>\n");
      out.write("            <button class=\"btn btn-info\"><i class=\"fa fa-file-pdf-o\"></i> Export as PDF</button>\n");
      out.write("        </div>\n");
      out.write("        <hr>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"invoice overflow-auto\">\n");
      out.write("        <div style=\"min-width: 600px\">\n");
      out.write("            <header>\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col\">\n");
      out.write("                        <a target=\"_blank\" href=\"Index.jsp\">\n");
      out.write("                            <img src=\"dummy/invoicelogo.jpg\" data-holder-rendered=\"true\" />\n");
      out.write("                            </a>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col company-details\">\n");
      out.write("                        <h2 class=\"name\">\n");
      out.write("                            <a target=\"_blank\" href=\"Index.jsp\">\n");
      out.write("                            Motor Insurance\n");
      out.write("                            </a>\n");
      out.write("                        </h2>\n");
      out.write("                        <div>Pune, EON Free Zone </div>\n");
      out.write("                        <div>Kharadi, Pune</div>\n");
      out.write("                        <div>Maharashtra 411014</div>\n");
      out.write("                        <div>motorinsurance@outlook.com</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </header>\n");
      out.write("            <main>\n");
      out.write("                <div class=\"row contacts\">\n");
      out.write("                    \n");
      out.write("                    <div class=\"col invoice-details\">\n");
      out.write("                        <h1 class=\"invoice-id\">INVOICE 3-2-1</h1>\n");
      out.write("                        <div class=\"date\">");
      out.print( (new java.util.Date()).toLocaleString());
      out.write("</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("                    <thead>\n");
      out.write("                        <tr>\n");
      out.write("                            <th>#</th>\n");
      out.write("                            <th class=\"text-left\">DESCRIPTION</th>\n");
      out.write("                            <th class=\"text-right\">TOTAL</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                        <tr>\n");
      out.write("                            <td class=\"no\">01</td>\n");
      out.write("                            <td class=\"text-left\"><h3>IDV</h3>Insured Declared Value</td>\n");
      out.write("                            <td class=\"total\">$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idv}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td class=\"no\">02</td>\n");
      out.write("                            <td class=\"text-left\"><h3>Basic Premium</h3>Basic Premium Without Taxes</td>\n");
      out.write("                            <td class=\"total\">$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${netPremium}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td class=\"no\">03</td>\n");
      out.write("                            <td class=\"text-left\"><h3>Risk Tax</h3>Only For Commercial Vehical </td>\n");
      out.write("                            <td class=\"total\">$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Commercial}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td class=\"no\">04</td>\n");
      out.write("                            <td class=\"text-left\"><h3>road Tax</h3>Road and Toll Tax</td>\n");
      out.write("                            <td class=\"total\">$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roadTax}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("                        </tr>\n");
      out.write("                    </tbody>\n");
      out.write("                    <tfoot>\n");
      out.write("                        <tr>\n");
      out.write("                            <td colspan=\"0\"></td>\n");
      out.write("                            <td colspan=\"0\">SUBTOTAL</td>\n");
      out.write("                            <td>$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${subtotal}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td colspan=\"0\"></td>\n");
      out.write("                            <td colspan=\"0\">TAX 18%</td>\n");
      out.write("                            <td>$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gst}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td colspan=\"0\"></td>\n");
      out.write("                            <td colspan=\"0\">Grant Premium</td>\n");
      out.write("                            <td>$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${premium}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("                        </tr>\n");
      out.write("                    </tfoot>\n");
      out.write("                </table>\n");
      out.write("                <div class=\"thanks\">Thank you!</div>\n");
      out.write("                <div class=\"notices\">\n");
      out.write("                    <div>NOTICE:</div>\n");
      out.write("                    <div class=\"notice\">Please Insured Your Car with Us \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </main>\n");
      out.write("            <footer>\n");
      out.write("                Invoice was created on a computer and is valid without the signature and seal.\n");
      out.write("            </footer>\n");
      out.write("        </div>\n");
      out.write("        <!--DO NOT DELETE THIS div. IT is responsible for showing footer always at the bottom-->\n");
      out.write("        <div></div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
